export default {
  pagination: {
    totalResults: 123,
    begin: 1,
    end: 24,
    currentPage: 1,
    totalPages: 6,
    previousPage: 0,
    nextPage: 2,
    perPage: 24,
    defaultPerPage: 24,
  },
  sorting: {
    options: [
      {
        field: "relevance",
        direction: "desc",
        label: "Best Match",
      },
      {
        field: "title",
        direction: "asc",
        label: "Name (A - Z)",
      },
      {
        field: "sales_rank",
        direction: "desc",
        label: "Most Popular",
      },
      {
        field: "price",
        direction: "desc",
        label: "Price ($$$ - $)",
      },
      {
        field: "price",
        direction: "asc",
        label: "Price ($ - $S$)",
      },
      {
        field: "title",
        direction: "desc",
        label: "Name (Z - A)",
      },
    ],
  },
  resultLayout: "grid",
  results: [
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVDTLTDTA0NDRiMARCIxMGQyNjhvSizBQA-_cKdQ",
      intellisuggestSignature:
        "84caaa3661e92a22af238bc0908873f0de8ac889f3747b5f6872708850e8c65b",
      ss_insights_quadrant: "Under Exposed",
      gross_margin: "33",
      ss_product_type: "Jeans",
      keywords:
        "cool, trendy, hip, skinny, skinnies, skinny jeans, skinny pants, colored jeans, colored pants, stretch, spandex, burgundy, purple, red, wine",
      color: ["Red"],
      multi_colors: "no",
      description:
        "As fine and flattering as these Burgundy Skinny Jeans are, you’ll find them to be All Purpose! Casual or a little more dressy, you’ll find a way to rock these skinnies! These skinny jeans feature standard 5-pockets design with rivets, a button zipper fly, and belt loops. • 75% Cotton, 23% Polyester, 2% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "All Purpose Burgundy Skinny Jeans",
      ss_clicks: "4453",
      color_family: ["Red"],
      sales_rank: "807",
      ss_sale_price: "59",
      ss_category_hierarchy: [
        "All Sale",
        "Gifts for Her",
        "All Sale&gt;50% off",
        "All Sale&gt;Bottoms on Sale",
      ],
      on_sale: "Yes",
      collection: "All Purpose",
      sale_price: "29.5",
      condition: "New",
      product_type: [
        "All Sale &gt; 50% off",
        "All Sale &gt; Bottoms on Sale",
        "All Sale",
        "Gifts for Her",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "95",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "44",
      uid: "156770",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/844a8130_thumb_med.jpg",
      price: "59",
      msrp: "75",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/844a8130_large.jpg",
      popularity: "807",
      name: "All Purpose Burgundy Skinny Jeans",
      product_type_unigram: "jeans",
      id: "cefb0bb66ce1c70e5616cc7a715c2df3",
      sku: "C-JU-R6-P1112",
      brand: "Just USA",
      url: "/product/C-JU-R6-P1112",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVdTfWDTA0sDRmMGQwYjAyYTA0MmZIL8pMAQD7RQpw",
      intellisuggestSignature:
        "4b205b5b209b6d1577ef541368e1f4efba865836927310f24a53a08d877fc7a5",
      ss_insights_quadrant: "Best Performer",
      gross_margin: "66",
      ss_product_type: "Jeans",
      keywords:
        "Grey Skinny Jeans, Grey, Gray, Skinny Jeans, Jeans, Denim, Skinnies, Classic Denim",
      color: ["Gray"],
      multi_colors: "no",
      description:
        "Show that amazing style is one of your Basic Instincts with these amazing Grey Skinny Jeans! It just comes natural! These skinny jeans feature standard 5 pocket styling, a zipper button fly, and belt loops. • 49% Rayon, 32% Cotton, 17% Polyester, 2% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "Basic Instincts Gray Skinny Jeans",
      ss_clicks: "2244",
      color_family: ["Gray"],
      sales_rank: "1513",
      ss_sale_price: "49",
      ss_category_hierarchy: [
        "All Sale",
        "Gifts for Her",
        "All Sale&gt;50% off",
        "Gifts for Her&gt;Gifts Under $50",
        "All Sale&gt;Bottoms on Sale",
      ],
      on_sale: "Yes",
      collection: "Basic Instincts",
      sale_price: "24.5",
      condition: "New",
      product_type: [
        "All Sale &gt; 50% off",
        "All Sale &gt; Bottoms on Sale",
        "All Sale",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "104",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "81",
      uid: "159835",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/rdb_studio_7_20_162000_thumb_med.jpg",
      price: "49",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/rdb_studio_7_20_162000_large.jpg",
      popularity: "1513",
      name: "Basic Instincts Gray Skinny Jeans",
      product_type_unigram: "jeans",
      id: "fcfa494d52659a22f486fe68b71732cb",
      sku: "C-JU-G3-P1093",
      brand: "Just USA",
      url: "/product/C-JU-G3-P1093",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrV9TTXDTA0MDRkMGQwZjAyYTA0MmZIL8pMAQD7LApt",
      intellisuggestSignature:
        "e824f544400afbe3301266195ffa532afeb72c3a4fdce483ad94e5f41744166b",
      ss_insights_quadrant: "Over Exposed",
      gross_margin: "68",
      ss_product_type: "Jeans",
      keywords:
        "Wide Leg Jeans, Denim, Jeans, Wide Leg Denim, Wide Leg, Flares, Flare Pants, Bell Bottoms, Flare Jeans, Flare Denim",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "Be indisputably cute and fabulous in our Classic And Contemporary Distressed Wide Leg Jeans. Paired with pumps, these stunning wide leg jeans will give you legs for days. Dressed up or down, anytime of the year, these classics will stand the test of time. Distressed bell bottom jeans feature standard functional pockets on front and back and a zipper button closure. • 73% Cotton, 14% Rayon, 11% Polyester, 2% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "Classic And Contemporary Distressed Wide Leg Jeans",
      ss_clicks: "2458",
      color_family: ["Blue"],
      sales_rank: "3660",
      ss_sale_price: "62",
      ss_category_hierarchy: [
        "All Sale",
        "Gifts for Her",
        "All Sale&gt;50% off",
        "All Sale&gt;Bottoms on Sale",
      ],
      on_sale: "Yes",
      sale_price: "31",
      condition: "New",
      product_type: [
        "All Sale &gt; 50% off",
        "All Sale &gt; Bottoms on Sale",
        "All Sale",
        "Gifts for Her",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "141",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "2",
      uid: "139290",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/524_2997_copyright_reddressboutique_2016_thumb_med.jpg",
      price: "62",
      msrp: "75",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/524_2997_copyright_reddressboutique_2016_large.jpg",
      popularity: "3660",
      name: "Classic And Contemporary Distressed Wide Leg Jeans",
      product_type_unigram: "jeans",
      id: "81173cc31c0fe52c4c936404b33044c4",
      sku: "C-JU-I7-P1011",
      brand: "Just USA",
      url: "/product/C-JU-I7-P1011",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrV9TTX9QowNTJgMGQwYTAyYTA0MmZIL8pMAQD9hwqM",
      intellisuggestSignature:
        "97418bcc73d2ce3caaa27673ed27e8e97799b8d47c7ba3d7421853fd89ca7d63",
      ss_insights_quadrant: "Under Exposed",
      gross_margin: "41",
      ss_product_type: "Jeans",
      keywords:
        "short jeans, ankle jeans, distressed, ripped, hole, cropped, crop, comfy, staple, denim",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "These coveted distressed Dark Wash Cropped Jeans are all about Easy Does It. Just as the name implies, these are easy on the eyes, easy to get on, and just oh-so stylish to boot! We are sure that they will be a staple in your wardrobe for years to come. These distressed cropped skinny jeans feature standard 5 pocket styling with a zipper and button closure. Model is wearing a size 25. • 98% Cotton, 2% Spandex • Machine Wash Cold • Unlined • Imported",
      title: "Easy Does It Dark Wash Cropped Jeans",
      ss_clicks: "2525",
      color_family: ["Blue"],
      sales_rank: "2677",
      ss_sale_price: "46",
      ss_category_hierarchy: [
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
      ],
      on_sale: "Yes",
      sale_price: "15",
      condition: "New",
      product_type: ["Gifts for Her", "Gifts for Her &gt; Gifts Under $50"],
      size: ["1", "3", "5", "7", "9", "11", "13"],
      material: "Cotton",
      days_since_published: "37",
      size_pants: ["1", "3", "5", "7", "9", "11", "13"],
      quantity_available: "21",
      uid: "139431",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/rd_studio_7_22_16_0779_thumb_med.jpg",
      price: "46",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/rd_studio_7_22_16_0779_large.jpg",
      popularity: "2677",
      name: "Easy Does It Dark Wash Cropped Jeans",
      product_type_unigram: "jeans",
      id: "7838bdfb8bffaecb1e48dfd0a34322b8",
      sku: "C-JU-I7-JP520",
      brand: "Just USA",
      url: "/product/C-JU-I7-JP520",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDWDXbS9TTTDTY3NGUwZDBlMDJhMDQyZkgvykwBAPDMCkE",
      intellisuggestSignature:
        "10015add8417609b3ae82eb05294eacc2f549d0d3726e8a0fa98f729de0b673c",
      ss_insights_quadrant: "Best Performer",
      gross_margin: "67",
      ss_product_type: "Jeans",
      keywords:
        "jeans, skinny, skinnies, skinny pants, pants, denim, faded, blue",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "Can you keep a secret or are you a Gossip Girl, looking fashionably chatty in these Faded Indigo Skinny Jeans? You’re always in the know of the current news, and you’re always willing to dish out on the latest scoop. So let’s cut to the chase and face the facts already: you’re a Gossip Girl. So Miss Chatter-Box, won’t you tell us the tall tale of where you got your perfect jeans? We’re all dying to know, and we all need to have a pair now. These jeans feature 5-pocket styling and a zipper/button-fly. Model wears a size 25. • 98% Cotton, 2% Spandex • Machine Wash Cold • Unlined • Imported",
      title: "Gossip Girl Faded Indigo Skinny Jeans",
      ss_clicks: "4028",
      color_family: ["Blue"],
      sales_rank: "804",
      ss_sale_price: "39",
      ss_category_hierarchy: [
        "All Sale",
        "Gifts for Her",
        "All Sale&gt;50% off",
        "Gifts for Her&gt;Gifts Under $50",
        "All Sale&gt;Bottoms on Sale",
      ],
      on_sale: "Yes",
      collection: "Gossip Girl",
      sale_price: "19",
      condition: "New",
      product_type: [
        "All Sale &gt; 50% off",
        "All Sale &gt; Bottoms on Sale",
        "All Sale",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "155",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "11",
      uid: "137724",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/264_9905_copyright_reddressboutique_2016_thumb_med.jpg",
      price: "39",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/264_9905_copyright_reddressboutique_2016_large.jpg",
      popularity: "804",
      name: "Gossip Girl Faded Indigo Skinny Jeans",
      product_type_unigram: "jeans",
      id: "f13f1b7df7c6226d74f9eabe4e0c33ea",
      sku: "C-SB-I6-S715",
      brand: "Scarlet Boulevard",
      url: "/product/C-SB-I6-S715",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDWDXbS9TTTDTY3sGAwZDBjMDJhMDQyZkgvykwBAPD6CkQ",
      intellisuggestSignature:
        "471578a2001375d0a20ef897d41e37bdaac12ba45da5b64e2167d545b26338a8",
      ss_insights_quadrant: "Under Exposed",
      gross_margin: "69",
      ss_product_type: "Jeans",
      keywords:
        "jeans, pants, skinny jeans, skinnies, denim, denim pants, dark jeans, dark wash",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "Can you keep a secret or are you a Gossip Girl, looking fashionably chatty in these Ultra Dark Wash Skinny Jeans? You’re always in the know of the current news, and you’re always willing to dish out on the latest scoop. So let’s cut to the chase and face the facts already: you’re a Gossip Girl. So Miss Chatter-Box, won’t you tell us the tall tale of where you got your perfect jeans? We’re all dying to know, and we all need to have a pair now. Denim pants feature 5-pocket styling, zipper/button-fly. • 92% Cotton, 6% Polyester, 2% Spandex • Machine Wash Cold • Unlined • Imported",
      title: "Gossip Girl Ultra Dark Wash Skinny Jeans",
      ss_clicks: "466",
      color_family: ["Blue"],
      sales_rank: "4333",
      ss_sale_price: "39",
      ss_category_hierarchy: [
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
      ],
      on_sale: "Yes",
      collection: "Gossip Girl",
      sale_price: "15",
      condition: "New",
      product_type: ["Gifts for Her", "Gifts for Her &gt; Gifts Under $50"],
      size: ["24", "25", "26", "27", "28", "29", "30"],
      material: "Denim",
      days_since_published: "83",
      size_pants: ["24", "25", "26", "27", "28", "29", "30"],
      quantity_available: "1",
      uid: "106779",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/844a7106_1_thumb_med.jpg",
      price: "39",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/844a7106_1_large.jpg",
      popularity: "4333",
      name: "Gossip Girl Ultra Dark Wash Skinny Jeans",
      product_type_unigram: "jeans",
      id: "1b0f88f594fd3e810192efe32abc288b",
      sku: "C-SB-I6-S708",
      brand: "Scarlet Boulevard",
      url: "/product/C-SB-I6-S708",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVdTXXDTA0MDZhMGQwZzACUkbGDOlFmSkA-1cKcg",
      intellisuggestSignature:
        "3b7860c6cdea2d38916e9172860ec4df15f8c8340eb67dcf96bb26bd1e8d58e2",
      ss_insights_quadrant: "Poor Performer",
      gross_margin: "60",
      ss_product_type: "Jeans",
      keywords:
        "jeans, pants, jeggings- skinnies, skinny jean, skinny pants, colored denim, colored jeans, distressed denim, distressed jeans, distressed pants, ripped knees, ripped jeans, ripped pants, green, dark green, pine green, evergreen, just usa",
      color: ["Green"],
      multi_colors: "no",
      description:
        "Always on the run, Off She Goes, with her great style in stride, in these Pine Green Skinny Jeans! Girl’s got places to go, things to do, and people to see, and she’ll look just as great (or even better) as the time she’s having in these amazing jeans! These skinny jeans feature standard 5 pocket styling, belt loops, a zipper button fly, and rips at the knees. Model is wearing a 25. • 75% Cotton, 23% Polyester, 2% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "Off She Goes Pine Green Skinny Jeans",
      ss_clicks: "402",
      color_family: ["Green"],
      sales_rank: "2841",
      ss_sale_price: "58",
      ss_category_hierarchy: [
        "All Sale",
        "Gifts for Her",
        "All Sale&gt;50% off",
        "All Sale&gt;Bottoms on Sale",
      ],
      on_sale: "Yes",
      sale_price: "29",
      condition: "New",
      product_type: [
        "All Sale &gt; 50% off",
        "All Sale &gt; Bottoms on Sale",
        "All Sale",
        "Gifts for Her",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "109",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "11",
      uid: "154533",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/844a7398_thumb_med.jpg",
      price: "58",
      msrp: "75",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/844a7398_large.jpg",
      popularity: "2841",
      name: "Off She Goes Pine Green Skinny Jeans",
      product_type_unigram: "jeans",
      id: "3b6f5843ceaaf2458d347697171ee75c",
      sku: "C-JU-E7-P1034",
      brand: "Just USA",
      url: "/product/C-JU-E7-P1034",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrV9TTVDTA0MDJkMGSwYDAyYTA0MmZIL8pMAQD7UQpx",
      intellisuggestSignature:
        "1696b297865f9eb27d2c9628923a420f350ba217544828c2e1160525843b9d3a",
      ss_insights_quadrant: "Under Exposed",
      gross_margin: "71",
      ss_product_type: "Jeans",
      keywords:
        "Skinny Jeans, Jeans, Denim, Medium Wash, Blue Jeans, Jeggings, Skinnies, Skinny Pants, Pants",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "Sometimes you just have to sit back and take it One Day At A Time, but with these Medium Blue Skinny Jeans on, at least you'll be doing it stylishly! Denim features 5 pocket styling, double belt loop detail in the back, wash detail under pockets. • 73% Cotton, 14% Rayon, 11% Polyester, 2% Spandex. • Machine wash cold. Tumble dry low. • Unlined • Made in the USA. Inseam: Size 24 Measures: 31&quot;, Size 25 measures 31.5&quot;, Size 26 Measures: 31.5&quot;, Size 27 measures 32&quot;,Size 28 Measures: 32&quot;, Size 29 Measures: 32.5&quot;, Size 30 measures 32.5&quot; Length: Size 24 Measures: 39.5&quot;, Size 25 measures 39.5&quot;, Size 26 Measures: 40&quot;, Size 27 measures 41&quot;,Size 28 Measures: 42&quot;, Size 29 Measures: 42&quot;, Size 30 measures 42&quot; Waist: Size 24 Measures: 29&quot;, Size 25 measures 29&quot;, Size 26 Measures: 31&quot;, Size 27 measures 31&quot;,Size 28 Measures: 32&quot;, Size 29 Measures: 33&quot;, Size 30 measures 34&quot;",
      title: "One Day At A Time Medium Blue Skinny Jeans",
      ss_clicks: "1952",
      color_family: ["Blue"],
      sales_rank: "231",
      ss_sale_price: "54",
      ss_category_hierarchy: ["Gifts for Her"],
      on_sale: "Yes",
      sale_price: "27",
      condition: "New",
      product_type: ["Gifts for Her"],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Denim",
      days_since_published: "157",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "2",
      uid: "139599",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/6b9a8997_thumb_med.jpg",
      price: "54",
      msrp: "75",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/6b9a8997_large.jpg",
      popularity: "231",
      name: "One Day At A Time Medium Blue Skinny Jeans",
      product_type_unigram: "jeans",
      id: "9c1b04b1bd08079714bfeb9261bf4b58",
      sku: "C-JU-I5-P1021",
      brand: "Just USA",
      url: "/product/C-JU-I5-P1021",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVdTXTDTA0MDBjMGSwZDAyYTA0MmZIL8pMAQD7Rgpy",
      intellisuggestSignature:
        "7d78d7a4fb4912264bf712d58286fbbbe224340d214ff44792c969d9a159844d",
      ss_insights_quadrant: "Poor Performer",
      gross_margin: "65",
      ss_product_type: "Jeans",
      keywords:
        "skinny jeans, skinnie jeans, skinnies, skinny pants, skinnie, spandex, jeggings, jeans",
      color: ["Olive"],
      multi_colors: "no",
      description:
        "Only the brave and proud need to come forward and make these Stand Tall Olive Green Skinny Jeans come to life! Once they’re gracing your frame, the slight urge to Stand Tall is sure to come over a beauty who may only be 5’1”, but feels 5’10” like Cindy Crawford! Don’t be the girl who is not giving the look of a few extra inches of height by missing out on these jeans that come with that quality!! These skinny jeans feature standard 5-pockets with rivets, belt loops, and a button zipper fly. • 55% Rayon, 26% Cotton, 18% Polyester, 1% Spandex • Machine wash cold. • Unlined • Made in the USA",
      title: "Stand Tall Olive Green Skinny Jeans",
      ss_clicks: "2735",
      color_family: ["Green"],
      sales_rank: "560",
      ss_sale_price: "48",
      ss_category_hierarchy: [
        "All Sale",
        "Gifts for Her",
        "All Sale&gt;50% off",
        "Gifts for Her&gt;Gifts Under $50",
        "All Sale&gt;Bottoms on Sale",
      ],
      on_sale: "Yes",
      sale_price: "24",
      condition: "New",
      product_type: [
        "All Sale &gt; 50% off",
        "All Sale &gt; Bottoms on Sale",
        "All Sale",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "28",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "6",
      uid: "160288",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/478a3325_2_thumb_med.jpg",
      price: "48",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/478a3325_2_large.jpg",
      popularity: "560",
      name: "Stand Tall Olive Green Skinny Jeans",
      product_type_unigram: "jeans",
      id: "a338292bb15a82c27b8851147be77157",
      sku: "C-JU-E6-P1006",
      brand: "Just USA",
      url: "/product/C-JU-E6-P1006",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVdTfVDTA0MDBjMGQwNGAwMmEwNDJmSC_KTAEABT8Kmw",
      intellisuggestSignature:
        "76fdf21ae8016de2af100f352ebf2350b01fcbbbc2665b9a152b058364b4590d",
      ss_insights_quadrant: "Under Exposed",
      gross_margin: "56",
      ss_product_type: "Jeans",
      keywords:
        "Skinny Jeans, Skinnies, Grey, Gray, Storm Grey, Dark Grey, Charcoal, Denim, Jeans, Jeggings, Classic",
      color: ["Gray"],
      multi_colors: "no",
      description:
        "Stand Tall in these stunning Storm Grey Skinny Jeans, and don’t look down unless it’s to admire your shoes! You’ll be holding your head high and setting the style standard way up there when you’re in these amazing jeans! These skinny jeans feature standard 5-pockets with rivets and a button zipper fly. • 55% Rayon, 26% Cotton, 18% Polyester, 1% Spandex • Machine wash cold. • Unlined • Made in the USA",
      title: "Stand Tall Storm Gray Skinny Jeans",
      ss_clicks: "1206",
      color_family: ["Gray"],
      sales_rank: "900",
      ss_sale_price: "48",
      ss_category_hierarchy: [
        "All Sale",
        "Gifts for Her",
        "All Sale&gt;50% off",
        "Gifts for Her&gt;Gifts Under $50",
        "All Sale&gt;Bottoms on Sale",
      ],
      on_sale: "Yes",
      sale_price: "24",
      condition: "New",
      product_type: [
        "All Sale &gt; 50% off",
        "All Sale &gt; Bottoms on Sale",
        "All Sale",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "7",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "16",
      uid: "171076",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/rdb_studio_2_3343_thumb_med.jpg",
      price: "48",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/rdb_studio_2_3343_large.jpg",
      popularity: "900",
      name: "Stand Tall Storm Gray Skinny Jeans",
      product_type_unigram: "jeans",
      id: "d54a306f75d9121bab89246e51e6d7df",
      sku: "C-JU-G5-P1006",
      brand: "Just USA",
      url: "/product/C-JU-G5-P1006",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDWDfbz1vU01Q2wNDGzZDBkMDRkMDJhMDQyZkgvykwBABTCCwA",
      intellisuggestSignature:
        "0440f084bdfb7ce03eea6883dca2b2d076209fd6c16646393b081c11d3e7a5eb",
      ss_insights_quadrant: "Poor Performer",
      gross_margin: "36",
      ss_product_type: "Jeans",
      keywords:
        "jeans, denim, blue jeans, distressed, distressed jeans, fray, frayed ends, frayed jeans, dark wash, dark denim, skinny jeans",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "The versatility of distressed skinny jeans is one of the greatest things on earth--right next to oxford button down shirts and cardigans. This pair in particular is a favorite of ours. It's trendy, but will stay in style for years to come. It can be dressed up and down, and frankly, it looks cool as all get out. They're the kind of jeans we can see ourselves falling asleep on the couch in after a few too many drinks (and likely will, if girls' night goes as planned). Model is wearing a size 1. • 98% Cotton 2% Spandex • Machine Wash Cold • Unlined • Imported",
      collection: "Above The Fray",
      title: "Above The Fray Dark Wash Distressed Skinny Jeans",
      ss_clicks: "3122",
      color_family: ["Blue"],
      condition: "New",
      sales_rank: "1295",
      ss_sale_price: "42",
      product_type: [
        "Style Influencer &gt; Lauren Lefevre",
        "All Bottoms &gt; Denim",
        "Shop By Trend &gt; So Seventies",
        "Shop By Trend",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["1", "3", "5", "7", "9", "11", "13"],
      material: "Cotton",
      days_since_published: "53",
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Denim",
        "Style Influencer",
        "All Bottoms",
        "Style Influencer&gt;Lauren Lefevre",
        "Gifts for Her",
        "Shop By Trend&gt;So Seventies",
        "Gifts for Her&gt;Gifts Under $50",
      ],
      on_sale: "No",
      quantity_available: "20",
      uid: "178121",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/478a3281_1_thumb_med.jpg",
      price: "42",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/478a3281_1_large.jpg",
      popularity: "1295",
      name: "Above The Fray Dark Wash Distressed Skinny Jeans",
      product_type_unigram: "jeans",
      id: "07118d6bf97afaf2eb4d2ef566c30f6d",
      sku: "C-SNK-I5-P9469",
      brand: "Sneak Peek",
      url: "/product/C-SNK-I5-P9469",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDWDfbz1g031A2wNDU2ZTBkMDRiMDIBksYM6UWZKQAVYAsF",
      intellisuggestSignature:
        "d11dfdbaa48948ebd89b890f4534b30aec7d6b524609e9bd1f39ee8706f8fb4f",
      ss_insights_quadrant: "Poor Performer",
      gross_margin: "51",
      ss_product_type: "Jeans",
      keywords:
        "jeans, denim, white jeans, distressed, distressed jeans, fray, frayed ends, frayed jeans, white wash, white denim, skinny jeans",
      color: ["White"],
      multi_colors: "no",
      description:
        "The versatility of distressed skinny jeans is one of the greatest things on earth--right next to oxford button down shirts and cardigans. This pair in particular is a favorite of ours. It's trendy, but will stay in style for years to come. It can be dressed up and down, and frankly, it looks cool as all get out. They're the kind of jeans we can see ourselves falling asleep on the couch in after a few too many drinks (and likely will, if girls' night goes as planned). Model is wearing a size 1. • 98% Cotton 2% Spandex • Machine Wash Cold • Unlined • Imported",
      collection: "Above The Fray",
      title: "Above The Fray White Distressed Skinny Jeans",
      ss_clicks: "1730",
      color_family: ["White"],
      condition: "New",
      sales_rank: "2990",
      ss_sale_price: "42",
      product_type: [
        "Shop By Trend &gt; So Seventies",
        "Shop By Trend &gt; White Haute",
        "All Bottoms &gt; Denim",
        "Shop By Trend &gt; Summer Staples",
        "Shop By Trend",
        "What's New",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["1", "3", "5", "7", "9", "11", "13"],
      material: "Cotton",
      days_since_published: "21",
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Denim",
        "Shop By Trend&gt;Summer Staples",
        "All Bottoms",
        "What's New",
        "Gifts for Her",
        "Shop By Trend&gt;So Seventies",
        "Gifts for Her&gt;Gifts Under $50",
        "Shop By Trend&gt;White Haute",
      ],
      on_sale: "No",
      quantity_available: "42",
      uid: "182922",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/5506_copyright_reddressboutique_2017__thumb_med.jpg",
      price: "42",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/5506_copyright_reddressboutique_2017__large.jpg",
      popularity: "2990",
      name: "Above The Fray White Distressed Skinny Jeans",
      product_type_unigram: "jeans",
      id: "a469061a0b865d29ad5b96838ca29450",
      sku: "C-SNK-W1-P9535",
      brand: "Sneak Peek",
      url: "/product/C-SNK-W1-P9535",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVdTfXDTA0NDRiMGQwNGYwMmEwNDJmSC_KTAEABXUKng",
      intellisuggestSignature:
        "472a15276461c1869b53fc7c314f2b9ba36dec4e776541319e39022d010c15bd",
      ss_insights_quadrant: "Over Exposed",
      gross_margin: "71",
      ss_product_type: "Jeans",
      keywords:
        "cool, trendy, hip, skinny, skinnies, skinny jeans, skinny pants, colored jeans, colored pants, stretch, spandex, black",
      color: ["Black"],
      multi_colors: "no",
      description:
        "Fit for the occasion whether it’s casual or a little dressy, these amazing Black Skinny Jeans are All Purpose! They’ll be your no-fail, go-to staple piece! These skinny jeans feature standard 5-pockets design with rivets, a button zipper fly, and belt loops. • 75% Cotton, 23% Polyester, 2% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "All Purpose Black Skinny Jeans",
      ss_clicks: "1169",
      color_family: ["Black"],
      sales_rank: "2330",
      ss_sale_price: "59",
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Denim",
        "Shop By Trend&gt;Comfy Casual",
        "All Bottoms",
        "Shop By Trend&gt;Gameday Looks&gt;Gameday Looks-Red &amp; Black",
        "Brands We Love&gt;Just USA + Just Black",
        "Gifts for Her",
        "Shop By Trend&gt;Gameday Looks&gt;Gameday Looks-Black",
        "Brands We Love",
        "Shop By Trend&gt;Gameday Looks",
      ],
      on_sale: "No",
      collection: "All Purpose",
      condition: "New",
      product_type: [
        "Shop By Trend &gt; Gameday Looks &gt; Gameday Looks-Black",
        "Shop By Trend &gt; Gameday Looks &gt; Gameday Looks-Red &amp; Black",
        "Shop By Trend &gt; Gameday Looks",
        "Shop By Trend &gt; Comfy Casual",
        "Brands We Love &gt; Just USA + Just Black",
        "All Bottoms &gt; Denim",
        "Gifts for Her",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "176",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "7",
      uid: "171844",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/rdb_studio_2_3361_thumb_med.jpg",
      price: "59",
      msrp: "75",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/rdb_studio_2_3361_large.jpg",
      popularity: "2330",
      name: "All Purpose Black Skinny Jeans",
      product_type_unigram: "jeans",
      id: "ecc097ba410b57d8169bd393bbe203ec",
      sku: "C-JU-G7-P1112",
      brand: "Just USA",
      url: "/product/C-JU-G7-P1112",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVdTXTDTA0NDRiMGQwNGEwMmEwNDJmSC_KTAEABTgKnA",
      intellisuggestSignature:
        "1da2f11fe812f6f64b8569e13f7a689a84a5897515d1e06305f4a7f93136c6d8",
      ss_insights_quadrant: "Best Performer",
      gross_margin: "35",
      ss_product_type: "Jeans",
      keywords:
        "cool, trendy, hip, skinny, skinnies, skinny jeans, skinny pants, colored jeans, colored pants, stretch, spandex, green, pine green",
      color: ["Green"],
      multi_colors: "no",
      description:
        "Fit for the occasion whether it’s casual or a little dressy, these amazing Pine Green Skinny Jeans are All Purpose! They’ll be your no-fail, go-to staple piece! These skinny jeans feature standard 5-pockets design with rivets, a button zipper fly, and belt loops. • 75% Cotton, 23% Polyester, 2% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "All Purpose Pine Green Skinny Jeans",
      ss_clicks: "37",
      color_family: ["Green"],
      sales_rank: "2743",
      ss_sale_price: "59",
      ss_category_hierarchy: [
        "All Bottoms&gt;Pants",
        "All Bottoms&gt;Denim",
        "All Bottoms",
        "Brands We Love&gt;Just USA + Just Black",
        "Gifts for Her",
        "Brands We Love",
      ],
      on_sale: "No",
      collection: "All Purpose",
      condition: "New",
      product_type: [
        "Brands We Love &gt; Just USA + Just Black",
        "All Bottoms &gt; Pants",
        "All Bottoms &gt; Denim",
        "All Bottoms",
        "Gifts for Her",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "88",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "79",
      uid: "173575",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/rdb_studio_2_3295_thumb_med.jpg",
      price: "59",
      msrp: "75",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/rdb_studio_2_3295_large.jpg",
      popularity: "2743",
      name: "All Purpose Pine Green Skinny Jeans",
      product_type_unigram: "jeans",
      id: "68084f6b93afe50b036893f9a42bbfe8",
      sku: "C-JU-E6-P1112",
      brand: "Just USA",
      url: "/product/C-JU-E6-P1112",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrV9TTXDTA0sDRmMGQwNGUwMmEwNDJmSC_KTAEABlcKqg",
      intellisuggestSignature:
        "95f241a1cbec43f26fa09e959cbc017c568659a8268ef994b613a6edaac13ce0",
      ss_insights_quadrant: "Best Performer",
      gross_margin: "41",
      ss_product_type: "Jeans",
      keywords:
        "Dark Wash Skinny Jeans, Dark Wash, Skinny Jeans, Jeans, Denim, Skinnies, Classic Denim",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "The only crime you’ll be guilty of in these Basic Instincts Dark Wash Skinny Jeans is looking fly! And the only thing you’ll be killing is the style game! These skinny jeans feature standard 5 pocket styling, a zipper button fly, and belt loops. • 49% Rayon, 32% Cotton, 17% Polyester, 2% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "Basic Instincts Dark Wash Skinny Jeans",
      ss_clicks: "3318",
      color_family: ["Blue"],
      sales_rank: "4338",
      ss_sale_price: "49",
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Pants",
        "All Bottoms&gt;Denim",
        "Shop By Trend&gt;Comfy Casual",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
      ],
      on_sale: "No",
      collection: "Basic Instincts",
      condition: "New",
      product_type: [
        "Shop By Trend &gt; Comfy Casual",
        "All Bottoms &gt; Pants",
        "All Bottoms &gt; Denim",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "8",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "54",
      uid: "168434",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/187_3556_copyright_reddressboutique_2016_thumb_med.jpg",
      price: "49",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/187_3556_copyright_reddressboutique_2016_large.jpg",
      popularity: "4338",
      name: "Basic Instincts Dark Wash Skinny Jeans",
      product_type_unigram: "jeans",
      id: "d2f845f65af3b41b0f3e417f24103c5b",
      sku: "C-JU-I7-P1093",
      brand: "Just USA",
      url: "/product/C-JU-I7-P1093",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrV9TTRdQqwNLNgMGQwNGMwMmEwNDJmSC_KTAEACEgKxA",
      intellisuggestSignature:
        "11c321c3b212709727cdc815f65142912db5e7f0b0d462b59b6a73bab1d79447",
      ss_insights_quadrant: "Poor Performer",
      gross_margin: "44",
      ss_product_type: "Jeans",
      keywords:
        "high waist, skinnies, indigo wash, indigo, blue jeans, medium blue, skinny jeans, cool, trendy, chic, high-waisted",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "C'est Chic, these lovely Medium Blue High Waisted Skinny Jeans are as classy and cute as you. Covering up yet showcasing gorgeous gams like yours, these streamlined skinnies are made for a graceful gal like you. These high waisted skinny jeans feature 5 pocket styling and a zipper button fly. • 75% Cotton, 23% Polyester, 2% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "C'est Chic Medium Blue High Waisted Skinny Jeans",
      ss_clicks: "3261",
      color_family: ["Blue"],
      sales_rank: "1859",
      ss_sale_price: "48",
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Pants",
        "All Bottoms&gt;Denim",
        "All Bottoms",
        "Going Fast",
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
      ],
      on_sale: "No",
      collection: "C'est Chic",
      condition: "New",
      product_type: [
        "All Bottoms &gt; Denim",
        "All Bottoms &gt; Pants",
        "Shop By Trend",
        "Going Fast",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "51",
      size_pants: ["25", "26", "27", "28", "29", "30", "31"],
      quantity_available: "4",
      uid: "157997",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/478a9560_thumb_med.jpg",
      price: "48",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/478a9560_large.jpg",
      popularity: "1859",
      name: "C'est Chic Medium Blue High Waisted Skinny Jeans",
      product_type_unigram: "jeans",
      id: "d0498843b4ddac4ef6dc63a25774cd2d",
      sku: "C-JU-I4-BP968",
      brand: "Just USA",
      url: "/product/C-JU-I4-BP968",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrV9TTR9QqwMLZkMGQwNGcwMmEwNDJmSC_KTAEACMoKyg",
      intellisuggestSignature:
        "98e707739aa321916128424eb1f505fdfc03cf27008b45a49fcc947ad91e7157",
      ss_insights_quadrant: "Over Exposed",
      gross_margin: "43",
      ss_product_type: "Jeans",
      keywords:
        "jeans, skinny jeans, skinnies, distressed, ripped, frayed, hem, denim, edgy",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "Feel like being on the Cutting Edge of fashion, but can't afford $1500 for a pair of jeans? We're right there with you (some of us paid less than that for our first car). Meet our Cutting Edge Distressed Skinny Jeans. They've got just the right amount of attitude for just the right price. Wear them with pride. And style, of course. These medium wash jeans feature distressing at the knees and thighs, fraying at the hem, a button and zipper fly and a standard 5- pockets with rivets. Model is wearing a size 1. • 98% Cotton 2% Spandex • Machine Wash Cold • Unlined • Imported",
      title: "Cutting Edge Medium Wash Distressed Skinny Jeans",
      ss_clicks: "764",
      color_family: ["Blue"],
      condition: "New",
      sales_rank: "2774",
      ss_sale_price: "44",
      product_type: [
        "Style Influencer &gt; Lynlee Poston",
        "All Bottoms &gt; Pants",
        "All Bottoms &gt; Denim",
        "Going Fast",
        "What's New",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["1", "3", "5", "7", "9", "11", "13"],
      material: "Cotton",
      days_since_published: "73",
      ss_category_hierarchy: [
        "All Bottoms&gt;Pants",
        "All Bottoms&gt;Denim",
        "Style Influencer&gt;Lynlee Poston",
        "Style Influencer",
        "All Bottoms",
        "Going Fast",
        "What's New",
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
      ],
      on_sale: "No",
      quantity_available: "2",
      uid: "180209",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/3383_copyright_reddressboutique_2017_thumb_med.jpg",
      price: "44",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/3383_copyright_reddressboutique_2017_large.jpg",
      popularity: "2774",
      name: "Cutting Edge Medium Wash Distressed Skinny Jeans",
      product_type_unigram: "jeans",
      id: "ababcb3f3730fff05b4d1c8b912783c3",
      sku: "C-JU-I4-JP839",
      brand: "Just USA",
      url: "/product/C-JU-I4-JP839",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDWdQ7Q9TTTNTAwCIlkMGQwtGAwMmEwNDJmSC_KTAEABvMKwA",
      intellisuggestSignature:
        "0ba87fa437b2e9efa2cb4128243d32c15bdc6b3e327098cd7901c898cf9a148e",
      ss_insights_quadrant: "Over Exposed",
      gross_margin: "44",
      ss_product_type: "Sign",
      keywords:
        "jeans, pants, jeggings, skinnies, skinny jean, skinny pants, denim, colored jeans, distressed denim, distressed jeans, distressed pants, ripped knees, ripped jeans, ripped pants, dark wash, dark denim, celebrity pink",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "He's over there in the corner, eyeing you, watching you enjoying your poison of choice while you chat with your girlfriends. He's impossibly handsome. Rugged features. A five o'clock shadow, dark hair that brushes his jawline. You can't tell what color his eyes are, only that they're glued to your Distressed Skinny Jeans and your smile. Are you sending out a Distress Signal or something else? Guess it's time to tell because he's coming this way. Game time ... it's a good thing you warmed up your rapier wit before leaving the house. These dark wash skinny jeans feature slight distressing at the knees and thighs, a button and zipper fly and standard 5- pockets with rivets. Model is wearing a size 1. • 95% Cotton 4% Polyester 1% Spadex • Machine Wash Cold • Unlined • Imported",
      title: "Distress Signal Dark Wash Distressed Skinny Jeans",
      ss_clicks: "897",
      color_family: ["Blue"],
      condition: "New",
      sales_rank: "1117",
      ss_sale_price: "39",
      product_type: [
        "Shop By Trend &gt; Comfy Casual",
        "All Bottoms &gt; Pants",
        "All Bottoms &gt; Denim",
        "Shop By Trend",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["1", "3", "5", "7", "9", "11", "13"],
      material: "Cotton",
      days_since_published: "131",
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Pants",
        "All Bottoms&gt;Denim",
        "Shop By Trend&gt;Comfy Casual",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
      ],
      on_sale: "No",
      quantity_available: "44",
      uid: "180195",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/3232_copyright_reddressboutique_2017_thumb_med.jpg",
      price: "39",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/3232_copyright_reddressboutique_2017_large.jpg",
      popularity: "1117",
      name: "Distress Signal Dark Wash Distressed Skinny Jeans",
      product_type_unigram: "jeans",
      id: "da193db0c3af068e27b94bc7b78a692f",
      sku: "C-CP-I6-000TY",
      brand: "Celebrity",
      url: "/product/C-CP-I6-000TY",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrV9TTVDQg2MjVkAEJLBiMTBkMjY4b0oswUAAjdCso",
      intellisuggestSignature:
        "f97e3e4f7a816399234aa0c2e3bedc0372a446d5b2ab9aa62b5c91b65f92df5c",
      ss_insights_quadrant: "Over Exposed",
      gross_margin: "41",
      ss_product_type: "Jeans",
      keywords:
        "Medium Blue, Blue, Distressed, Distressed Skinny Jeans, Skinny Jeans, Jeans, Skinnies, Distressed Jeans, Medium Blue Jeans, Denim",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "Don't Stress It, distress it with these magnificent Medium Blue Distressed Skinny Jeans! You won’t have to worry about your look reflecting your frazzled mind on a trying day with these sightly jeans. They’ll keep on looking pristine even if you feel anything but! These distressed skinny jeans feature standard 5 pocket styling, belt loops, a button zipper fly, and distressing on the front. • 98% Cotton, 2% Spandex • Hand Wash Cold • Unlined • Made in the USA",
      title: "Don't Stress It Medium Blue Distressed Skinny Jeans",
      ss_clicks: "3675",
      color_family: ["Blue"],
      condition: "New",
      sales_rank: "1889",
      ss_sale_price: "48",
      product_type: [
        "Shop By Trend &gt; Comfy Casual",
        "All Bottoms &gt; Pants",
        "All Bottoms &gt; Denim",
        "Shop By Trend",
        "Going Fast",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["1", "3", "5", "7", "9", "11", "13"],
      material: "Cotton",
      days_since_published: "79",
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Pants",
        "All Bottoms&gt;Denim",
        "Shop By Trend&gt;Comfy Casual",
        "All Bottoms",
        "Going Fast",
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
      ],
      on_sale: "No",
      quantity_available: "5",
      uid: "157919",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/460_4409_copyright_reddressboutique_2016_thumb_med.jpg",
      price: "48",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/460_4409_copyright_reddressboutique_2016_large.jpg",
      popularity: "1889",
      name: "Don't Stress It Medium Blue Distressed Skinny Jeans",
      product_type_unigram: "jeans",
      id: "920cf47c60b66ca1f8237f9b2fcd2a53",
      sku: "C-JU-I5-PS251",
      brand: "Just USA",
      url: "/product/C-JU-I5-PS251",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrV9TTXdQkwNjRiMGQwMmAwMmEwNDJmSC_KTAEABzkKsw",
      intellisuggestSignature:
        "1e1829b0b36a01230e6f9bf8614bca025fe37db1c081fd56f65f367acd5cb6ca",
      ss_insights_quadrant: "Under Exposed",
      gross_margin: "75",
      ss_product_type: "Jeans",
      keywords:
        "Distressed Skinny Jeans, Denim, Skinny Jeans, Distressed, Distressed Jeans, Distressed Denim, Dark Wash, Dark Wash Jeans, Dark Wash Denim, Staple",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "There's literally nothing better in the whole world than Distressed Skinny Jeans (in my personal opinion), and these are positively the coolest pair ever. They go with just about everything, and they look great on almost everyone (hey, I said almost everyone). How could you turn these down? They're calling your name and they won't wait long. Consider them like your soulmates, but really impatient ones that could sell out at any moment. And pretend that sentence made total sense, because in our heads it did. Model is wearing a 25. • 60% Cotton 38% Rayon 2% Spandex • Machine Wash Cold • Unlined • Imported",
      title: "Elevate The Everyday Dark Wash Distressed Skinny Jeans",
      ss_clicks: "2773",
      color_family: ["Blue"],
      condition: "New",
      sales_rank: "2025",
      ss_sale_price: "49",
      product_type: [
        "Brands We Love &gt; Just USA + Just Black",
        "Shop By Trend &gt; Comfy Casual",
        "All Bottoms &gt; Denim",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "143",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Denim",
        "Shop By Trend&gt;Comfy Casual",
        "All Bottoms",
        "Brands We Love&gt;Just USA + Just Black",
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
        "Brands We Love",
      ],
      on_sale: "No",
      quantity_available: "26",
      uid: "178976",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/1107__copyright_reddressboutique_thumb_med.jpg",
      price: "49",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/1107__copyright_reddressboutique_large.jpg",
      popularity: "2025",
      name: "Elevate The Everyday Dark Wash Distressed Skinny Jeans",
      product_type_unigram: "jeans",
      id: "9896b688e338f5e6106a28cf0777852b",
      sku: "C-JU-I7-DP312",
      brand: "Just USA",
      url: "/product/C-JU-I7-DP312",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVdTfXdQowNPBiMGQwAiITBkMjY4b0oswUAAhdCsU",
      intellisuggestSignature:
        "6a9991c304167ad58c18739124acfcc26453a68d3a73f59bb2243cca1b1c6101",
      ss_insights_quadrant: "Poor Performer",
      gross_margin: "59",
      ss_product_type: "Jeans",
      keywords:
        "black, jeans, skinnies, distressed, ripped, hole, denim, everyday, every day",
      color: ["Black"],
      multi_colors: "no",
      description:
        "Ever Cool and always stunning, you’ll look incredible each time you put on these Black Distressed Skinny Jeans! These super soft and chic jeans are great any time of the year! These skinny jeans feature standard 5 pocket styling, belt loops, button fly closure, and distressed detail on the front. • 52% Rayon, 26% Cotton, 21% Polyester, 1% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "Ever Cool Black Distressed Skinny Jeans",
      ss_clicks: "658",
      color_family: ["Black"],
      condition: "New",
      sales_rank: "3845",
      ss_sale_price: "48",
      product_type: [
        "Shop By Trend &gt; Comfy Casual",
        "Shop By Trend &gt; Girl's Night Out",
        "Brands We Love &gt; Just USA + Just Black",
        "All Bottoms &gt; Pants",
        "All Bottoms &gt; Denim",
        "Style Influencer &gt; Cortney Dryden",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "4",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      ss_category_hierarchy: [
        "Shop By Trend",
        "Shop By Trend&gt;Girl's Night Out",
        "All Bottoms&gt;Pants",
        "All Bottoms&gt;Denim",
        "Style Influencer&gt;Cortney Dryden",
        "Shop By Trend&gt;Comfy Casual",
        "All Bottoms",
        "Style Influencer",
        "Brands We Love&gt;Just USA + Just Black",
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
        "Brands We Love",
      ],
      on_sale: "No",
      quantity_available: "51",
      uid: "178924",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/17_03_01_studio_020505copyright_reddressboutique__1_thumb_med.jpg",
      price: "48",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/17_03_01_studio_020505copyright_reddressboutique__1_large.jpg",
      popularity: "3845",
      name: "Ever Cool Black Distressed Skinny Jeans",
      product_type_unigram: "jeans",
      id: "3f2c9f9e48d0a14dc29d3863682c783a",
      sku: "C-JU-G7-BP10J",
      brand: "Just USA",
      url: "/product/C-JU-G7-BP10J",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVDTfUdQowNPBiMGQwMmIwMmEwNDJmSC_KTAEACWoK0A",
      intellisuggestSignature:
        "5fcdfb67c5802a767856aa9fe519f74b03f60347428e73c3a6e9f78c04a9ea71",
      ss_insights_quadrant: "Poor Performer",
      gross_margin: "52",
      ss_product_type: "Jeans",
      keywords:
        "white, jeans, skinnies, distressed, ripped, hole, denim, everyday, every day",
      color: ["White"],
      multi_colors: "no",
      description:
        "Ever Cool and always stunning, you’ll look incredible each time you put on these White Distressed Skinny Jeans! These super soft and chic jeans are great any time of the year! These skinny jeans feature standard 5 pocket styling, belt loops, button fly closure, and distressed detail on the front. • 52% Rayon, 26% Cotton, 21% Polyester, 1% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "Ever Cool White Distressed Skinny Jeans",
      ss_clicks: "2954",
      color_family: ["White"],
      condition: "New",
      sales_rank: "3304",
      ss_sale_price: "48",
      product_type: [
        "Shop By Trend &gt; Comfy Casual",
        "Shop By Trend &gt; Summer Staples",
        "Style Influencer &gt; Cortney Dryden",
        "Brands We Love &gt; Just USA + Just Black",
        "All Bottoms &gt; Denim",
        "All Bottoms &gt; Pants",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "28",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Pants",
        "Style Influencer&gt;Cortney Dryden",
        "All Bottoms&gt;Denim",
        "Shop By Trend&gt;Comfy Casual",
        "Shop By Trend&gt;Summer Staples",
        "Style Influencer",
        "All Bottoms",
        "Brands We Love&gt;Just USA + Just Black",
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
        "Brands We Love",
      ],
      on_sale: "No",
      quantity_available: "16",
      uid: "171303",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/rdb_studio_2_3221_thumb_med.jpg",
      price: "48",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/rdb_studio_2_3221_large.jpg",
      popularity: "3304",
      name: "Ever Cool White Distressed Skinny Jeans",
      product_type_unigram: "jeans",
      id: "9711b3faabbfb2aa230d0985152372f2",
      sku: "C-JU-W1-BP10J",
      brand: "Just USA",
      url: "/product/C-JU-W1-BP10J",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDWDXbS9TTXDTY3MGQwZDAyZjAyYTAEUulFmSkA-pQKbQ",
      intellisuggestSignature:
        "b0529ad69432d61cd6728d6a7ef29fe84b575c14cbf22736d2511a8ad2b1e4fd",
      ss_insights_quadrant: "Over Exposed",
      gross_margin: "47",
      ss_product_type: "Jeans",
      keywords:
        "denim, jeans, skinnies, skinny jeans, basic, staple, casual, cool, fall, back to school, blue, dark blue, dark wash, versatile",
      color: ["Blue"],
      multi_colors: "no",
      description:
        "These Dark Wash Skinny Jeans are so flattering and versatile that they’ll be your Everyday Pick! You can’t go wrong with these sightly skinnies! These dark wash skinny jeans feature standard 5 pocket styling, belt loops, zipper button fly closure, whiskering, and a light fade around the knees. • 98% Cotton, 2% Spandex • Machine Wash Cold • Unlined • Imported",
      title: "Everyday Pick Dark Wash Skinny Jeans",
      ss_clicks: "3032",
      color_family: ["Blue"],
      sales_rank: "2895",
      ss_sale_price: "38",
      season: "Fall",
      ss_category_hierarchy: [
        "Shop By Trend",
        "All Bottoms&gt;Pants",
        "All Bottoms&gt;Denim",
        "All Bottoms",
        "What's New",
        "Gifts for Her",
        "Gifts for Her&gt;Gifts Under $50",
      ],
      on_sale: "No",
      condition: "New",
      product_type: [
        "All Bottoms &gt; Denim",
        "All Bottoms &gt; Pants",
        "Shop By Trend",
        "What's New",
        "All Bottoms",
        "Gifts for Her",
        "Gifts for Her &gt; Gifts Under $50",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30"],
      material: "Cotton",
      days_since_published: "89",
      size_pants: ["24", "25", "26", "27", "28", "29", "30"],
      quantity_available: "23",
      uid: "158078",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/rdb_studio_2_4288_thumb_med.jpg",
      price: "38",
      msrp: "50",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/rdb_studio_2_4288_large.jpg",
      popularity: "2895",
      name: "Everyday Pick Dark Wash Skinny Jeans",
      product_type_unigram: "jeans",
      id: "18e3009dd3901ecafbe7eba30ee9e212",
      sku: "C-SB-I7-S701",
      brand: "Scarlet Boulevard",
      url: "/product/C-SB-I7-S701",
    },
    {
      intellisuggestData:
        "eJwrTs4tNM9jYMhKTcwrZnDW9QrVdTfXdQowtfRiMGQwMgEhQyNjhvSizBQACX8K1Q",
      intellisuggestSignature:
        "e64b55c4a78c5619bdcf4fb4c0bebe02378877a09a4e9f6cd4a9b8a19da788fd",
      ss_insights_quadrant: "Under Exposed",
      gross_margin: "55",
      ss_product_type: "Jeans",
      keywords:
        "black, jeans, skinnies, distressed, ripped, hole, denim, everyday, every day, black skinny jeans",
      color: ["Black"],
      multi_colors: "no",
      description:
        "You've never been one to play the damsel in distress before, and you're certainly not about to start doing it now. I mean, there's this guy at the office and he's just so delicious. It would be wonderful if someone would go ahead and take him off the table so you could stop thinking about him already. Well, you heard that he's into this whole, rescue the princess thing and you definitely don't need to be rescued. Though, he could seriously give any Hemsworth a run for his money ... so maybe you could slip into these 'distressed' skinny jeans after work one night and just try to make it work. Oh, those abs. I mean come on, for crying out loud. You wouldn't even need a washing machine. Might be worth pretending to need help changing a tire or something. • 52% Rayon, 26% Cotton, 21% Polyester, 1% Spandex • Machine Wash Cold • Unlined • Made in the USA",
      title: "New Level Black Distressed Skinny Jeans",
      ss_clicks: "1489",
      color_family: ["Black"],
      condition: "New",
      sales_rank: "512",
      ss_sale_price: "55",
      product_type: [
        "Shop By Trend &gt; Girl's Night Out",
        "Shop By Trend &gt; Comfy Casual",
        "Brands We Love &gt; Just USA + Just Black",
        "All Bottoms &gt; Pants",
        "All Bottoms &gt; Denim",
        "Shop By Trend &gt; Summer Staples",
        "Gifts for Her",
      ],
      size: ["24", "25", "26", "27", "28", "29", "30", "31"],
      material: "Cotton",
      days_since_published: "26",
      size_pants: ["24", "25", "26", "27", "28", "29", "30", "31"],
      ss_category_hierarchy: [
        "Shop By Trend",
        "Shop By Trend&gt;Girl's Night Out",
        "All Bottoms&gt;Pants",
        "All Bottoms&gt;Denim",
        "Shop By Trend&gt;Comfy Casual",
        "Shop By Trend&gt;Summer Staples",
        "All Bottoms",
        "Brands We Love&gt;Just USA + Just Black",
        "Gifts for Her",
        "Brands We Love",
      ],
      on_sale: "No",
      quantity_available: "48",
      uid: "180056",
      thumbnailImageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_thumb_med/3010_copyright_reddressboutique_2017_thumb_med.jpg",
      price: "55",
      msrp: "75",
      imageUrl:
        "https://searchspring-demo-content.s3.amazonaws.com/demo/fashion/product_images_large/3010_copyright_reddressboutique_2017_large.jpg",
      popularity: "512",
      name: "New Level Black Distressed Skinny Jeans",
      product_type_unigram: "jeans",
      id: "da6c16a09cc7ebc6209fe14d76bd5bb2",
      sku: "C-JU-G7-BP59J",
      brand: "Just USA",
      url: "/product/C-JU-G7-BP59J",
    },
  ],
  facets: [
    {
      field: "color_family",
      label: "Color",
      type: "palette",
      multiple: "multiple-union",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "Blue",
          label: "Blue",
          count: 87,
        },
        {
          active: false,
          type: "value",
          value: "Black",
          label: "Black",
          count: 7,
        },
        {
          active: false,
          type: "value",
          value: "White",
          label: "White",
          count: 7,
        },
        {
          active: false,
          type: "value",
          value: "Red",
          label: "Red",
          count: 5,
        },
        {
          active: false,
          type: "value",
          value: "Gray",
          label: "Gray",
          count: 4,
        },
        {
          active: false,
          type: "value",
          value: "Green",
          label: "Green",
          count: 4,
        },
        {
          active: false,
          type: "value",
          value: "Orange",
          label: "Orange",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Pink",
          label: "Pink",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Purple",
          label: "Purple",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Yellow",
          label: "Yellow",
          count: 1,
        },
      ],
    },
    {
      field: "ss_category_hierarchy",
      label: "Category",
      type: "hierarchy",
      multiple: "single",
      collapse: 0,
      facet_active: 0,
      hierarchyDelimiter: ">",
      values: [
        {
          active: false,
          type: "value",
          value: "Gifts for Her",
          label: "Gifts for Her",
          count: 123,
        },
        {
          active: false,
          type: "value",
          value: "Shop By Trend",
          label: "Shop By Trend",
          count: 61,
        },
        {
          active: false,
          type: "value",
          value: "All Bottoms",
          label: "All Bottoms",
          count: 56,
        },
        {
          active: false,
          type: "value",
          value: "Brands We Love",
          label: "Brands We Love",
          count: 32,
        },
        {
          active: false,
          type: "value",
          value: "What's New",
          label: "What's New",
          count: 21,
        },
        {
          active: false,
          type: "value",
          value: "Style Influencer",
          label: "Style Influencer",
          count: 13,
        },
        {
          active: false,
          type: "value",
          value: "All Sale",
          label: "All Sale",
          count: 10,
        },
        {
          active: false,
          type: "value",
          value: "Going Fast",
          label: "Going Fast",
          count: 6,
        },
        {
          active: false,
          type: "value",
          value: "All Tops",
          label: "All Tops",
          count: 5,
        },
        {
          active: false,
          type: "value",
          value: "All Dresses",
          label: "All Dresses",
          count: 3,
        },
        {
          active: false,
          type: "value",
          value: "All Shoes",
          label: "All Shoes",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Back in Stock",
          label: "Back in Stock",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Memorial Day Sale",
          label: "Memorial Day Sale",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Notify of Restock",
          label: "Notify of Restock",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Playsuits",
          label: "Playsuits",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Valentine's Day",
          label: "Valentine's Day",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "White & Blue Looks",
          label: "White & Blue Looks",
          count: 1,
        },
      ],
    },
    {
      field: "price",
      label: "Price",
      type: "list",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "range",
          low: "20",
          high: "30",
          label: "$20 to $30",
          count: 3,
        },
        {
          active: false,
          type: "range",
          low: "30",
          high: "40",
          label: "$30 to $40",
          count: 40,
        },
        {
          active: false,
          type: "range",
          low: "40",
          high: "50",
          label: "$40 to $50",
          count: 53,
        },
        {
          active: false,
          type: "range",
          low: "50",
          high: "75",
          label: "$50 to $75",
          count: 26,
        },
        {
          active: false,
          type: "range",
          low: "100",
          high: "150",
          label: "$100 to $150",
          count: 1,
        },
        {
          active: false,
          type: "range",
          low: "150",
          high: "200",
          label: "$150 to $200",
          count: 3,
        },
      ],
    },
    {
      field: "size",
      label: "Size",
      type: "grid",
      multiple: "multiple-intersect",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "1",
          label: "1",
          count: 14,
        },
        {
          active: false,
          type: "value",
          value: "3",
          label: "3",
          count: 14,
        },
        {
          active: false,
          type: "value",
          value: "5",
          label: "5",
          count: 14,
        },
        {
          active: false,
          type: "value",
          value: "6",
          label: "6",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "7",
          label: "7",
          count: 16,
        },
        {
          active: false,
          type: "value",
          value: "8",
          label: "8",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "9",
          label: "9",
          count: 16,
        },
        {
          active: false,
          type: "value",
          value: "10",
          label: "10",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "11",
          label: "11",
          count: 14,
        },
        {
          active: false,
          type: "value",
          value: "13",
          label: "13",
          count: 14,
        },
        {
          active: false,
          type: "value",
          value: "15",
          label: "15",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "24",
          label: "24",
          count: 58,
        },
        {
          active: false,
          type: "value",
          value: "25",
          label: "25",
          count: 63,
        },
        {
          active: false,
          type: "value",
          value: "26",
          label: "26",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "27",
          label: "27",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "28",
          label: "28",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "29",
          label: "29",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "30",
          label: "30",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "31",
          label: "31",
          count: 53,
        },
        {
          active: false,
          type: "value",
          value: "X-Small",
          label: "X-Small",
          count: 15,
        },
        {
          active: false,
          type: "value",
          value: "Small",
          label: "Small",
          count: 42,
        },
        {
          active: false,
          type: "value",
          value: "Medium",
          label: "Medium",
          count: 42,
        },
        {
          active: false,
          type: "value",
          value: "Large",
          label: "Large",
          count: 42,
        },
        {
          active: false,
          type: "value",
          value: "X-Large",
          label: "X-Large",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "5.5",
          label: "5.5",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "6.5",
          label: "6.5",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "7.5",
          label: "7.5",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "8.5",
          label: "8.5",
          count: 2,
        },
      ],
    },
    {
      field: "brand",
      label: "Brand",
      type: "list",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "36point5",
          label: "36point5",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "American Bazi",
          label: "American Bazi",
          count: 3,
        },
        {
          active: false,
          type: "value",
          value: "Blu Pepper",
          label: "Blu Pepper",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Caribbean Queen",
          label: "Caribbean Queen",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Celebrity",
          label: "Celebrity",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Cello Jeans",
          label: "Cello Jeans",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "City Classified",
          label: "City Classified",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Dance & Marvel",
          label: "Dance & Marvel",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "E2 Clothing",
          label: "E2 Clothing",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Ellison",
          label: "Ellison",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "En Creme",
          label: "En Creme",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Everly",
          label: "Everly",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Flying Tomato",
          label: "Flying Tomato",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Fringe",
          label: "Fringe",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Hello Miss",
          label: "Hello Miss",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Hudson",
          label: "Hudson",
          count: 4,
        },
        {
          active: false,
          type: "value",
          value: "Hyfve",
          label: "Hyfve",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Just Black",
          label: "Just Black",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Just Panmaco",
          label: "Just Panmaco",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Just USA",
          label: "Just USA",
          count: 60,
        },
        {
          active: false,
          type: "value",
          value: "Love Stitch",
          label: "Love Stitch",
          count: 4,
        },
        {
          active: false,
          type: "value",
          value: "Lush",
          label: "Lush",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Miracle Miles",
          label: "Miracle Miles",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "On Twelfth",
          label: "On Twelfth",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "Scarlet Boulevard",
          label: "Scarlet Boulevard",
          count: 22,
        },
        {
          active: false,
          type: "value",
          value: "Signature 8",
          label: "Signature 8",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Sneak Peek",
          label: "Sneak Peek",
          count: 3,
        },
        {
          active: false,
          type: "value",
          value: "Staccato",
          label: "Staccato",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Uniq",
          label: "Uniq",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "Very J",
          label: "Very J",
          count: 1,
        },
      ],
    },
    {
      field: "on_sale",
      label: "On Sale",
      type: null,
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "No",
          label: "No",
          count: 75,
        },
        {
          active: false,
          type: "value",
          value: "Yes",
          label: "Yes",
          count: 48,
        },
      ],
    },
    {
      field: "material",
      label: "Material",
      type: "list",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "Denim",
          label: "Denim",
          count: 42,
        },
        {
          active: false,
          type: "value",
          value: "Cotton",
          label: "Cotton",
          count: 74,
        },
      ],
    },
    {
      field: "size_pants",
      label: "Pant Size",
      type: "list",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "1",
          label: "1",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "3",
          label: "3",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "5",
          label: "5",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "7",
          label: "7",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "9",
          label: "9",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "11",
          label: "11",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "13",
          label: "13",
          count: 2,
        },
        {
          active: false,
          type: "value",
          value: "24",
          label: "24",
          count: 58,
        },
        {
          active: false,
          type: "value",
          value: "25",
          label: "25",
          count: 63,
        },
        {
          active: false,
          type: "value",
          value: "26",
          label: "26",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "27",
          label: "27",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "28",
          label: "28",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "29",
          label: "29",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "30",
          label: "30",
          count: 65,
        },
        {
          active: false,
          type: "value",
          value: "31",
          label: "31",
          count: 53,
        },
      ],
    },
    {
      field: "size_dress",
      label: "Dress Size",
      type: "grid",
      multiple: "single",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "Large",
          label: "Large",
          count: 42,
        },
        {
          active: false,
          type: "value",
          value: "Medium",
          label: "Medium",
          count: 42,
        },
        {
          active: false,
          type: "value",
          value: "Small",
          label: "Small",
          count: 42,
        },
        {
          active: false,
          type: "value",
          value: "X-Large",
          label: "X-Large",
          count: 1,
        },
        {
          active: false,
          type: "value",
          value: "X-Small",
          label: "X-Small",
          count: 15,
        },
      ],
    },
    {
      field: "season",
      label: "Season",
      type: "list",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "Summer",
          label: "Summer",
          count: 11,
        },
        {
          active: false,
          type: "value",
          value: "Spring",
          label: "Spring",
          count: 8,
        },
        {
          active: false,
          type: "value",
          value: "Fall",
          label: "Fall",
          count: 4,
        },
      ],
    },
    {
      field: "pattern",
      label: "Pattern",
      type: "list",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "Embroidered",
          label: "Embroidered",
          count: 8,
        },
        {
          active: false,
          type: "value",
          value: "Stripe",
          label: "Stripe",
          count: 1,
        },
      ],
    },
    {
      field: "dress_length_name",
      label: "Dress Length",
      type: null,
      multiple: "multiple-union",
      collapse: 1,
      facet_active: 0,
      values: [
        {
          active: false,
          type: "value",
          value: "Above Knee",
          label: "Above Knee",
          count: 2,
        },
      ],
    },
  ],
  breadcrumbs: [
    {
      label: 'Search: "jeans"',
      filterLabel: "Search",
      filterValue: "jeans",
      removeFilters: [],
      removeRefineQuery: [],
    },
  ],
  filterSummary: [],
  merchandising: {
    redirect: "",
    is_elevated: [],
    elevated: [],
    removed: [],
    content: [],
    facets: [],
    facetsHide: [],
  },
  relatedQueries: null,
};
